Backend 7
blockchain-sonar/reminder pull request #10
Opened 2022-08-03 13:05 UTC by polina-tereschenko

2022-08-03 13:10 UTC, theanurin requested changes

2022-08-03 13:10 UTC, theanurin commented on blockchain_sonar_reminder_backend/bots/telegram/telegram_bot.py
> +
Why this tab presented?

2022-08-03 14:11 UTC, polina-tereschenko commented on blockchain_sonar_reminder_backend/bots/telegram/telegram_bot.py
> +
fixed

2022-08-08 10:22 UTC, theanurin approved these changes

2022-08-08 10:30 UTC, theanurin approved these changes, later dismissed

2022-08-08 13:22 UTC, bite322 approved these changes, later dismissed

2022-08-08 13:27 UTC, thedetukov submitted a review, later dismissed

2022-08-10 11:51 UTC, thedetukov approved these changes

2022-08-10 12:31 UTC, bite322 approved these changes

2022-08-11 12:14 UTC, merged